Add getSummaryData method to return thumbnail and title for summary s…
silverstripe/silverstripe-elemental-fileblock pull request #4
Opened 2018-08-02 02:23 UTC by raissanorth

…ection of ElementEditor

Required for https://github.com/dnadesign/silverstripe-elemental/pull/284 to allow the required data - content summary - to be pulled in via GraphQL

Requires https://github.com/dnadesign/silverstripe-elemental/pull/313

2018-08-02 02:30 UTC, ScopeyNZ requested changes

2018-08-02 02:30 UTC, ScopeyNZ commented on src/Block/FileBlock.php
> +        $summaryData = [];
You should use `$summaryData = parent::getSummaryData()` as a base.

2018-08-02 21:15 UTC, robbieaverill commented
Can you please add a `NEW` commit prefix?

2018-08-02 21:39 UTC, ScopeyNZ approved these changes

2018-08-02 21:39 UTC, ScopeyNZ commented
Happy now but I'm not sure if the new API is finalised yet on elemental.

2018-08-02 21:39 UTC, robbieaverill requested changes
Wait to merge until the elemental parent PR is

2018-08-03 04:39 UTC, robbieaverill requested changes
It's kind of unrelated to this PR, but can you please update the composer requirements (and in .travis.yml) to use SS 4.3 and elemental 4.x-dev, so that this code would actually get used in the right context when the automated tests are running

2018-08-12 23:01 UTC, robbieaverill approved these changes

2018-08-13 00:09 UTC, merged